In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv("../data/raw/world_cup_last_50_years.csv")

In [1]:
import os

print(os.getcwd())

c:\Users\hp\Downloads\world-cup-ai-predictor\notebooks

In [6]:
print(os.listdir())

['01_data_preprocessing.ipynb']

In [4]:
df.head()

,year,date,stage,home_team,away_team,home_goals,away_goals,winner,match_id
0,1974,1974-06-10,Quarter-finals,South Korea,Sweden,0,0,Draw,1
1,1974,1974-06-10,Quarter-finals,Ghana,Switzerland,2,0,Ghana,2
2,1974,1974-06-10,Group Stage,Sweden,Saudi Arabia,2,0,Sweden,3
3,1974,1974-06-10,Group Stage,Cameroon,Uruguay,2,1,Cameroon,4
4,1974,1974-06-10,Group Stage,Nigeria,Japan,2,1,Nigeria,5

In [5]:
df.shape

(832, 9)

In [6]:
df.columns

Index(['year', 'date', 'stage', 'home_team', 'away_team', 'home_goals',
       'away_goals', 'winner', 'match_id'],
      dtype='object')

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 832 entries, 0 to 831
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   year        832 non-null    int64
 1   date        832 non-null    object
 2   stage       832 non-null    object
 3   home_team   832 non-null    object
 4   away_team   832 non-null    object
 5   home_goals  832 non-null    int64
 6   away_goals  832 non-null    int64
 7   winner      832 non-null    object
 8   match_id    832 non-null    int64
dtypes: int64(4), object(5)
memory usage: 58.6+ KB

In [8]:
df.describe()

              year  home_goals  away_goals    match_id
count   832.000000  832.000000  832.000000  832.000000
mean   1998.000000    1.137019    1.090144  416.500000
std      14.975632    0.859841    0.880487  240.322006
min    1974.000000    0.000000    0.000000    1.000000
25%    1986.000000    1.000000    0.000000  208.750000
50%    1998.000000    1.000000    1.000000  416.500000
75%    2010.000000    2.000000    2.000000  624.250000
max    2022.000000    3.000000    3.000000  832.000000

In [9]:
df.isnull().sum()

year          0
date          0
stage         0
home_team     0
away_team     0
home_goals    0
away_goals    0
winner        0
match_id      0
dtype: int64

In [10]:
df.duplicated().sum()

np.int64(0)

In [11]:
df["date"] = pd.to_datetime(df["date"])

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 832 entries, 0 to 831
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   year        832 non-null    int64
 1   date        832 non-null    datetime64[ns]
 2   stage       832 non-null    object
 3   home_team   832 non-null    object
 4   away_team   832 non-null    object
 5   home_goals  832 non-null    int64
 6   away_goals  832 non-null    int64
 7   winner      832 non-null    object
 8   match_id    832 non-null    int64
dtypes: datetime64[ns](1), int64(4), object(4)
memory usage: 58.6+ KB

In [13]:
df["winner"].value_counts()

winner
Draw            258
Switzerland      26
Sweden           25
Iran             25
Netherlands      25
Ghana            24
Costa Rica       24
Italy            23
Argentina        23
USA              22
Japan            21
Brazil           19
Cameroon         19
Denmark          19
Portugal         18
France           18
Saudi Arabia     17
Egypt            17
Germany          17
Australia        16
Morocco          16
South Korea      16
Algeria          15
Nigeria          15
Mexico           15
England          15
Spain            14
Poland           13
Belgium          13
Croatia          12
Senegal          12
Uruguay          11
Tunisia           9
Name: count, dtype: int64

In [14]:
df = df.drop(columns=["home_goals", "away_goals"])

In [15]:
df = df.drop(columns=["match_id"])

In [17]:
df.to_csv("clean_world_cup.csv", index=False)