In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("../data/preprocessed/clean_world_cup.csv")

In [4]:
df.head()

   year        date           stage    home_team     away_team    winner
0  1974  1974-06-10  Quarter-finals  South Korea        Sweden      Draw
1  1974  1974-06-10  Quarter-finals        Ghana   Switzerland     Ghana
2  1974  1974-06-10     Group Stage       Sweden  Saudi Arabia    Sweden
3  1974  1974-06-10     Group Stage     Cameroon       Uruguay  Cameroon
4  1974  1974-06-10     Group Stage      Nigeria         Japan   Nigeria

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 832 entries, 0 to 831
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   year       832 non-null    int64
 1   date       832 non-null    object
 2   stage      832 non-null    object
 3   home_team  832 non-null    object
 4   away_team  832 non-null    object
 5   winner     832 non-null    object
dtypes: int64(1), object(5)
memory usage: 39.1+ KB

In [6]:
df = df.drop(columns=["date"])

In [7]:
X = df.drop("winner", axis=1)
y = df["winner"]

In [8]:
X.head()

   year           stage    home_team     away_team
0  1974  Quarter-finals  South Korea        Sweden
1  1974  Quarter-finals        Ghana   Switzerland
2  1974     Group Stage       Sweden  Saudi Arabia
3  1974     Group Stage     Cameroon       Uruguay
4  1974     Group Stage      Nigeria         Japan

In [9]:
y.head()

0        Draw
1       Ghana
2      Sweden
3    Cameroon
4     Nigeria
Name: winner, dtype: object

In [10]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [11]:
categorical_features = ["home_team", "away_team", "stage"]

In [12]:
categorical_features = ["home_team", "away_team", "stage"]

In [13]:
preprocessor = ColumnTransformer(
    transformers=[
        ("cat", OneHotEncoder(handle_unknown="ignore"), categorical_features)
    ],
    remainder="passthrough"
)

In [14]:
X_encoded = preprocessor.fit_transform(X)

In [15]:
print(type(X_encoded))

<class 'scipy.sparse._csr.csr_matrix'>

In [16]:
print(X_encoded.shape)

(832, 71)

In [17]:
print(df["home_team"].nunique())
print(df["away_team"].nunique())
print(df["stage"].nunique())

32
32
6

In [18]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X_encoded,
    y,
    test_size=0.2,
    random_state=42
)

In [19]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(665, 71)
(167, 71)
(665,)
(167,)